export const LOG_ACTIVITY = 'LOG_ACTIVITY';
export const LOG_ACTIVITY_START = 'LOG_ACTIVITY_START';
export const LOG_ACTIVITY_DONE = 'LOG_ACTIVITY_DONE';
export const LOG_ACTIVITY_ERROR = 'LOG_ACTIVITY_ERROR';
